services:
  backend:
    build: .
    container_name: django_todo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      backend_NAME: ${backend_NAME}
      backend_USER: ${backend_USER}
      backend_PASSWORD: ${backend_PASSWORD}
      backend_PORT: ${backend_PORT}
    env_file:
      - .env

  db:
    image: hub.hamdocker.ir/postgres:15
    container_name: postgres_db_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data: